---
title: "41903 Pset 3"
author: "Andrew McKinley, Lauren Mostrom, Pietro Ramella, Francisco Ruela, and Bohan Yang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(dplyr)
library(ggplot2)
library(lubridate)
library(data.table)
library(zoo)
library(tidyr)
library(ggpubr)
library(stargazer)
library(sandwich)
library(lmtest)
library(ivpack) # for IV
library(Matrix)
library(plm) # for panel data regressions
library(multiwayvcov) # for calculate clustered standard errors
library(texreg)
```

## Question 1


\newpage
## Question 2

### (a)
```{r}
setwd("C:/Users/17036/OneDrive/Documents/GitHub/metrics3-zombie-boards/Psets/3")
murder <- read.delim("PS3Data/MURDER_RAW.txt", header=FALSE)

colnames(murder) <- c('id','state','year','mrdrte','exec','unem','d90','d93',      
                      'cmrdrte','cexec','cunem','cexec1','cunem1')

# Use only data for 1990 and 1993
data <- murder %>%
  filter(year==90 | year==93)

reg_pooled <- lm(mrdrte~d93+exec+unem, data=data)
### calculate standard errors 
# standard homoskedastic standard errors
se.homo_pooled <- sqrt(diag(vcov(reg_pooled))) 
# robust standard errors
HCV.coef_pooled <- vcovHC(reg_pooled, type = 'HC1')
se.robust_pooled <- sqrt(diag(HCV.coef_pooled)) 
# clustered standard errors
CLCV.coef_pooled <- cluster.vcov(reg_pooled,data$state)
se.cluster_pooled <- sqrt(diag(CLCV.coef_pooled))
```


\newpage

```{r, results='asis'}
texreg(list(reg_pooled, reg_pooled, reg_pooled), digits=4, caption.above=TRUE,
       override.se = list(se.homo_pooled, se.robust_pooled, se.cluster_pooled),
       custom.model.names=c("Homoskedastic", "Robust", "Clustered"))
```


### (b)
In this setting FE and FD are numerically identical because there are only two time periods, 1990 and 1993.

### (c)
*First Differences*
```{r}
data_90 <- data %>%
  filter(year==90)
data_93 <- data %>%
  filter(year==93)
data_fd <- left_join(data_90,data_93,by=c("id"))
data_fd$delta_mrdrte <- data_fd$mrdrte.y-data_fd$mrdrte.x
data_fd$delta_exec <- data_fd$exec.y-data_fd$exec.x
data_fd$delta_unem <- data_fd$unem.y-data_fd$unem.x
reg_fd <- lm(delta_mrdrte~delta_exec+delta_unem, data=data_fd)
### calculate standard errors 
# standard homoskedastic standard errors
se.homo_fd <- sqrt(diag(vcov(reg_fd))) 
# robust standard errors
HCV.coef_fd <- vcovHC(reg_fd, type = 'HC1')
se.robust_fd <- sqrt(diag(HCV.coef_fd)) 
# clustered standard errors
CLCV.coef_fd <- cluster.vcov(reg_fd,data_fd$state.x)
se.cluster_fd <- sqrt(diag(CLCV.coef_fd))
```
\newpage
```{r, results='asis'}
texreg(list(reg_fd, reg_fd, reg_fd), digits=4, caption.above=TRUE,
       override.se = list(se.homo_fd,se.robust_fd,se.cluster_fd),
       custom.model.names=c("Homoskedastic", "Robust", "Clustered"))
```


*Fixed Effects*
```{r}
data_fe <- data %>%
  group_by(id) %>%
  mutate(mrdrte_demean = mrdrte-mean(mrdrte), exec_demean = exec-mean(exec), unem_demean = unem-mean(unem), d93_demean = d93-mean(d93))
reg_fe <- lm(mrdrte_demean~exec_demean+unem_demean+d93,data=data_fe)
### calculate standard errors 
# standard homoskedastic standard errors
se.homo_fe <- sqrt(diag(vcov(reg_fe))) 
# robust standard errors
HCV.coef_fe <- vcovHC(reg_fe, type = 'HC1')
se.robust_fe <- sqrt(diag(HCV.coef_fe)) 
# clustered standard errors
CLCV.coef_fe <- cluster.vcov(reg_fe,data_fe$state)
se.cluster_fe <- sqrt(diag(CLCV.coef_fe))
```
\newpage
```{r, results='asis'}
texreg(list(reg_fe, reg_fe, reg_fe), digits=4, caption.above=TRUE,
       override.se = list(se.homo_fe,se.robust_fe,se.cluster_fe),
       custom.model.names=c("Homoskedastic", "Robust", "Clustered"))
```


### (d)




\newpage
## Question 3




\newpage
## Question 4
